from scipy import signal
import matplotlib.pyplot as plt
import numpy as np

plt.figure()
b1, a1 = signal.bessel(2, 100, 'low', analog=True)
b2, a2 = signal.cheby1(2, 10, 100, 'low', analog=True)
w1, h1 = signal.freqs(b1, a1)
w2, h2 = signal.freqs(b2, a2)
plt.xlim([10, 1000])
plt.ylim([-60, 5])
plt.semilogx(w1, 20 * np.log10(abs(h1)))
plt.semilogx(w2, 20 * np.log10(abs(h2)))
plt.title('Tiefpass')
plt.xlabel('Frequenz [rad / s]')
plt.ylabel('Amplitude [dB]')
plt.grid(which='both', axis='both')
plt.savefig('lowpass.png')

plt.figure()
b1, a1 = signal.bessel(2, 100, 'high', analog=True)
b2, a2 = signal.cheby1(2, 10, 100, 'high', analog=True)
w1, h1 = signal.freqs(b1, a1)
w2, h2 = signal.freqs(b2, a2)
plt.xlim([10, 1000])
plt.ylim([-60, 5])
plt.semilogx(w1, 20 * np.log10(abs(h1)))
plt.semilogx(w2, 20 * np.log10(abs(h2)))
plt.title('Hochpass')
plt.xlabel('Frequenz [rad / s]')
plt.ylabel('Amplitude [dB]')
plt.grid(which='both', axis='both')
plt.savefig('highpass.png')

plt.figure()
b1, a1 = signal.bessel(2, (100,150), 'bandpass', analog=True)
w1, h1 = signal.freqs(b1, a1)
plt.xlim([10, 1000])
plt.ylim([-60, 5])
plt.semilogx(w1, 20 * np.log10(abs(h1)))
plt.title('Bandpass')
plt.xlabel('Frequenz [rad / s]')
plt.ylabel('Amplitude [dB]')
plt.grid(which='both', axis='both')
plt.savefig('bandpass.png')


plt.figure()
b1, a1 = signal.bessel(2, (100,150), 'bandstop', analog=True)
w1, h1 = signal.freqs(b1, a1)
plt.xlim([10, 1000])
plt.ylim([-60, 5])
plt.semilogx(w1, 20 * np.log10(abs(h1)))
plt.title('Bandstop')
plt.xlabel('Frequenz [rad / s]')
plt.ylabel('Amplitude [dB]')
plt.grid(which='both', axis='both')
plt.savefig('bandstop.png')

plt.show()